services:

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: MSPatient
      MYSQL_ROOT_PASSWORD: "!rjooont_12I"
    ports:
      - "3307:3306"
    networks:
      - ms-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p!rjooont_12I" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_DATABASE: MSNote
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "!rjooont_12I"
    ports:
      - "27018:27017"
    networks:
      - ms-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka:
    build: ./eureka
    ports:
      - "8761:8761"
    networks:
      - ms-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  patient:
    build: ./patient
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/MSPatient
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "!rjooont_12I"
    networks:
      - ms-network

  note:
    build: ./note
    ports:
      - "8082:8082"
    depends_on:
      mongodb:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - ms-network

  risk:
    build: ./risk
    ports:
      - "8083:8083"
    depends_on:
      - eureka
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - ms-network

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - ms-network

  front:
    build: ./front
    ports:
      - "8084:8084"
    depends_on:
      - gateway
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - ms-network

networks:
  ms-network:
