spring.application.name=patient

logging.level.org.springframework=INFO

################### DataSource Configuration ##########################
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/MSPatient
spring.datasource.username=root
spring.datasource.password=!rjooont_12I

################### Hibernate Configuration ##########################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
