spring.application.name=gateway

logging.level.org.springframework.cloud.gateway=DEBUG

server.port=8080

spring.cloud.gateway.mvc.routes[0].id=patient
spring.cloud.gateway.mvc.routes[0].uri=lb://patient
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/patient/**
spring.cloud.gateway.mvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.mvc.routes[1].id=note
spring.cloud.gateway.mvc.routes[1].uri=lb://note
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/note/**
spring.cloud.gateway.mvc.routes[1].filters[0]=StripPrefix=1